Repository nolebase/integrations, pull requests merged in 2024-04, with the labels that each got.

#174 docs: fixed a typo in git-changelog, styles.css -> style.css
  docs/pages/en/integrations/vitepress-plugin-git-changelog/getting-started.md
  docs/pages/zh-CN/integrations/vitepress-plugin-git-changelog/getting-started.md
Labels: documentation

#175 feat(git-changelog): include extensions option
  packages/vitepress-plugin-git-changelog/src/vite/git.ts
  packages/vitepress-plugin-git-changelog/src/vite/helpers.test.ts
  packages/vitepress-plugin-git-changelog/src/vite/helpers.ts
Labels: enhancement

#181 fix(ui): incorrect style exports
  docs/package.json
  docs/pages/en/ui/asciinema-player/index.md
  docs/pages/en/ui/lazy-teleport-rive-canvas/index.md
  docs/pages/zh-CN/ui/asciinema-player/index.md
  docs/pages/zh-CN/ui/lazy-teleport-rive-canvas/index.md
  docs/vite.config.ts
  packages/ui/build.config.ts
  packages/ui/package.json
  packages/vitepress-plugin-enhanced-readabilities/package.json
  packages/vitepress-plugin-enhanced-readabilities/src/client/index.ts
  packages/vitepress-plugin-git-changelog/package.json
  packages/vitepress-plugin-git-changelog/src/client/index.ts
  packages/vitepress-plugin-highlight-targeted-heading/package.json
  packages/vitepress-plugin-inline-link-preview/package.json
  packages/vitepress-plugin-inline-link-preview/src/client/index.ts
  packages/vitepress-plugin-og-image/package.json
  packages/vitepress-plugin-page-properties/package.json
  packages/vitepress-plugin-page-properties/src/client/index.ts
  packages/vitepress-plugin-thumbnail-hash/package.json
  pnpm-lock.yaml
Labels: bug
